import { StudyDifficulty, StudyLength } from "@/lib/constants";

// Mock Data Types
export interface SuggestedPlan {
  title: string;
  passageRefs: string;
  difficulty: StudyDifficulty;
  length: StudyLength;
}

export const suggestStudyPlan = async (topic: string): Promise<SuggestedPlan> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        title: `The Theology of ${topic}`,
        passageRefs: "Romans 8:28-39",
        difficulty: StudyDifficulty.INTERMEDIATE,
        length: StudyLength.MEDIUM
      });
    }, 1500);
  });
};

export const surpriseMe = async (): Promise<SuggestedPlan> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const plans = [
        { title: "The Suffering Servant", passageRefs: "Isaiah 53", difficulty: StudyDifficulty.INTRO, length: StudyLength.SHORT },
        { title: "Melchizedek's Order", passageRefs: "Hebrews 7", difficulty: StudyDifficulty.ADVANCED, length: StudyLength.LONG },
      ];
      resolve(plans[Math.floor(Math.random() * plans.length)]);
    }, 1000);
  });
};

export const generateFullStudy = async (
  title: string, 
  topic: string, 
  passages: string, 
  difficulty: StudyDifficulty, 
  length: StudyLength, 
  ownerId: string, 
  tier: any
): Promise<any> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      // Mock "Study" Object Structure
      resolve({
        metadata: {
          id: `mock-${Date.now()}`,
          title,
          theme: topic,
          passages,
          difficulty,
          length,
          ownerId,
          createdAt: Date.now(),
          isPublic: false,
          stats: { views: 0, likes: 0, shares: 0, clones: 0 }
        },
        content: {
           // We will fill this with dummy sections in the Editor view if needed
           theme_summary: "This is a placeholder summary generated by the mockup engine."
        }
      });
    }, 15000); // 15s delay to show off the "Reasoning" UI
  });
};

export const regenerateSection = async (sectionId: string, currentStudy: any, tier: any): Promise<string> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(`**Regenerated Insight for ${sectionId}**\n\nThis content has been refreshed by the logic engine. It provides deeper clarity on the subject, refined by your specific request context.\n\n> "Truth is not static but ever-revealing."\n\nNew application points:\n- Point A\n- Point B`);
        }, 3000);
    });
}

export const generateStudyImage = async (title: string, theme: string): Promise<string> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve("https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&q=80&w=1600");
        }, 4000);
    });
}
